spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.76.197:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: blog
    password: WcMZJzphrkSy6brC
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.yigumoyan.blogjava.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

BlogJava:
  domain: http://39.101.76.197
  prefix: /image/
  file-path: /root/image/